# Generated by Django 2.1 on 2018-08-15 02:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(default='', max_length=500)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 8, 15, 2, 50, 30, 102062, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 8, 15, 2, 50, 29, 929920, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(default='', max_length=500)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 8, 15, 2, 50, 30, 103062, tzinfo=utc))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='til.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Til',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(default='', max_length=500)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 8, 15, 2, 50, 30, 102062, tzinfo=utc))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='til.Post')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='til.Post'),
        ),
    ]
