# Generated by Django 2.1 on 2018-08-15 02:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('til', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 15, 2, 50, 45, 603066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 15, 2, 50, 45, 438949, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 15, 2, 50, 45, 603066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='til',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 15, 2, 50, 45, 602065, tzinfo=utc)),
        ),
    ]
